spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://skuhackathon-dev.cvnrrtf0fql4.ap-northeast-2.rds.amazonaws.com:3306/diary
    username: root
    password: kimsoyun1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        security:
          security:
            oauth2:
              client:
                registration:
                  google:
                    client-name: google
                    client-id: 534317406966-fr39qp43a9qoa87hd7hnveor4a3l8qdt.apps.googleusercontent.com
                    client-secret: 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
                    redirect-uri: http://localhost:8080/login/oauth2/code/google
                    authorization-grant-type: authorization_code
                    scope: profile, email
                  naver:
                    client-name: naver
                    client-id: KwquDcvwFXUYH1NjOt6d
                    client-secret: w8Vsq_iCaM
                    redirect-uri: http://localhost:8080/login/oauth2/code/naver
                    authorization-grant-type: authorization_code
                    scope: name, email
                provider:
                  naver:
                    authorization-uri: https://nid.naver.com/oauth2.0/authorize
                    token-uri: https://nid.naver.com/oauth2.0/token
                    user-info-uri: https://openapi.naver.com/v1/nid/me
                    user-name-attribute: response
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: skuhackathon-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIA6LCEA6ZU4LBMFOPH
      secretKey: 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
jwt-secret: ThisStatementISJwtSecretKeyDoNotUseThisStatement


openai:
  model: gpt-4o
  api:
    url: https://api.openai.com/v1/chat/completions
    key: sk-proj-uQpHjh3XcBEniaAbaZFiT3BlbkFJK9oIYzj09AR1tZ664jSx
